version: "3.8"
services:

  tcc_database:
    deploy:
      replicas: 1
    image: postgres:latest
    container_name: tcc_database
    ports:
      - "5432:5432"
    networks:
      - tcc-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tcc
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  tcc_backend:
    deploy:
      replicas: 1
    build: tcc-algorithm
    container_name: tcc_backend
    ports:
      - "8000:8000"
    networks:
      - tcc-network
    environment:
      CONFIG_MODE: "development"
      DEVELOPMENT_DATABASE_URL: "postgresql+psycopg2://postgres:123@tcc_database:5432/tcc"

  tcc_frontend:
    deploy: 
      replicas: 1
    build: tcc-frontend
    container_name: tcc_frontend
    ports:
      - "80:80"
    networks:
      - tcc-network

volumes:
  db_volume:
    driver: local

networks:
  tcc-network:
    name: tcc-network
    driver: bridge